#Input directory for fastq files
input_dir: "/path/to/fastq/files"

#Output directory for pipeline results
output_dir: "/path/to/output/directory"

#Specify the number of threads to use for parallel processing
threads: 4

#Reference genome and annotation files for annotation
reference:
 genome: "/path/to/reference/genome/"
 annotation: "/path/to/reference/genome.gtf"
 star_index: "/path/to/reference/genome/star_index"
 rRNA: "/path/to/reference/rrna.fasta"

#Tools that needs to be loaded
tools:
 bbduk: "/path/to/tools/bbmap_tools/bbduk.sh"
 featurecounts: "/path/to/tools/subread-2.1.0-macOS-x86_64/bin/featureCounts"

#Specify the formal for fastq files
files:
 pattern: "*_{1,2}.fq.gz"

